### ISSUE TITLE
how can i use this in Next Theme?

### ISSUE THREAD

**Issue by frontc** [FrontendSophie/hexo-infinite-scroll#1]
hello,
    as the title say, I use Next Theme，and I can't find head.ejs。then how can i do?

**Comment by FrontendSophie** [comment]
Sorry for the late response.

Just checked Next Theme. It used swig instead of ejs.  

Please find `hexo-theme-next/layout/_partials/head.swig` and then try to import.  Thanks.

If problems still remained, please do not hesitate to inform me : )
