### ISSUE TITLE
How to config in Hexo-theme-magnetic ?

### ISSUE THREAD

**Issue by sira313** [FrontendSophie/hexo-infinite-scroll#3]
Hi, where do i put the config location after i add the cdn to head.ejs? is that _config.yml, css, or something else?

**Comment by FrontendSophie** [comment]
Hi @sira313, you can config by passing parameters into `infiniteScroll();` in your `head.ejs`. 
```
infiniteScroll({
    pageSize: 12,
    loading: {
        style: 'line'
    }
});
```
😉

**Comment by sira313** [comment]
> Hi @sira313, you can config by passing parameters into `infiniteScroll();` in your `head.ejs`.
> 
> ```
> infiniteScroll({
>     pageSize: 12,
>     loading: {
>         style: 'line'
>     }
> });
> ```

I'm using [Hexo-theme-magnetic](https://github.com/klugjo/hexo-theme-magnetic).
I've tried to paste this code on `head.ejs`
```
<!-- Infinite Scroll-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/frontendsophie/hexo-infinite-scroll@1.0.0/dist/hexo-infinite-scroll.min.css">
<script src="https://cdn.jsdelivr.net/gh/frontendsophie/hexo-infinite-scroll@1.0.0/dist/hexo-infinite-scroll.min.js"></script>
<script>infiniteScroll({
    pageSize: 12,
    item: '.work',
    loading: {
        style: 'line'
    }
});</script>
```
but still doesn't work.
if you have any suggestion please help me.
sorry i didn't have experience with this plugin, i usually install plugin via npm.

**Comment by FrontendSophie** [comment]
@sira313 , just checked Hexo-theme-magnetic. Two suggestions for you:  
1. This plugin is jquery based. **Simply paste CDN below before the Infinite Scroll code.**
```
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
```
2.  Now the plugin can work. The loading animation is shown in the middle of the post section as default. While this magnetic theme has special layout, so I added a wrapper div for all the posts and set it `float: left` to open BFC mode. **Please find `layout/index.ejs` and use code below to replace the whole file.** 
```
<section class="main clearfix">
    <div style="float: left">
        <% page.posts.each(function(item){ %>
        <%- partial('_partial/article-index', {item: item}) %>
        <% }); %>
        <%- partial('_partial/pagination') %>
    </div>
</section>
```

**Comment by sira313** [comment]
wow, it's work! thank you very much. I'll take this a note to my blog 😊

**Comment by FrontendSophie** [comment]
My pleasure 😊.
