### ISSUE TITLE
How to make the loading animation become single loading in the columns post?

### ISSUE THREAD

**Issue by sira313** [FrontendSophie/hexo-infinite-scroll#4]
Hi, Sophie. I need your help to configure your plugins in [my theme](https://github.com/sira313/hexo-theme-griddy)
I use your plugins right now but with no animation 'cause the animation become many much as many post to show, it's bugs me.
How do i make it become a single loading animation just like instagram profile on desktop?
I add this on the head.ejs
```html
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/frontendsophie/hexo-infinite-scroll@1.0.0/dist/hexo-infinite-scroll.min.css">
<script src="https://cdn.jsdelivr.net/gh/frontendsophie/hexo-infinite-scroll@1.0.0/dist/hexo-infinite-scroll.min.js"></script>
<script>infiniteScroll({
    pageSize: 12,
    item: '.work',
    loading: false,
});</script>
```
to call "work" on my article-excerp.ejs
```html
<div class="column is-one-quarter-fullhd is-one-third-desktop is-one-third-tablet is-one-third-mobile is-gapless-mobile">   
    <div class="card work has-box-shadow">
        <figure class="image is-square">
            <a href="<%- config.root %><%- item.path %>">
            <img src="<%- item.cover_index || theme.default_cover_index %>" class="media has-rounded-corner" alt="<%- item.title %>"/>
            <div class="caption has-rounded-corner">
                <div class="work_title">
                    <h1><%- item.title || theme.default_post_title || "Untitled" %></h1>
                </div>
            </div>
            </a>
        </figure>
    </div>
</div>
```
Thank you

PS:
> Your plugin is not working on mobile device, i've tested your demo too on chome android new version on the different device too

**Comment by FrontendSophie** [comment]
Hi @sira313, sorry for the late response. Just checked your theme, `.column` should work.
```
 <script>
        infiniteScroll({
            item: '.column'
        });
 </script>
```
For the current mobile behavior, it should work in iOS. Cause I don't have an android phone maybe tomorrow borrow one and test 🤪. Anyway, thanks for the real test and advice. Will fix in next release.
BTW, nice theme😉.

**Comment by sira313** [comment]
> Hi @sira313, sorry for the late response. Just checked your theme, `.column` should work.
> 
> ```
>  <script>
>         infiniteScroll({
>             item: '.column'
>         });
>  </script>
> ```
> 
> For the current mobile behavior, it should work in iOS. Cause I don't have an android phone maybe tomorrow borrow one and test 🤪. Anyway, thanks for the real test and advice. Will fix in next release.
> BTW, nice theme.

thanks, it's work on the column class.
i'll be wait on the next update 😎
