### ISSUE TITLE
Name of the config section?

### ISSUE THREAD

**Issue by kristofzerbe** [FrontendSophie/hexo-infinite-scroll#5]
I want to use your lovely plugin, with slightly different settings, but ... whats the name of the config section for it? infinite_scroll?

**Comment by FrontendSophie** [comment]
Hi, thank you for your appreciation.

You can use it like below:
```
infiniteScroll({
    showNum: 10,
    style: 'ball-pulse'
})
```

**Comment by kristofzerbe** [comment]
Ah ok, I thought your tool can be configured by a section in the config.yml, as all Hexo plugins does. Is this possible to implement? I love to have all configuration in one place...

**Comment by FrontendSophie** [comment]
Sorry, I'm afraid cannot. As Hexo is static site generator which actually does not send any requests to fetch the content. In order to simulate the effect of the infinite scroll,  the script can only run on compiled files.
