### ISSUE TITLE
Uncaught Error: cannot find .post element

### ISSUE THREAD

**Issue by sunxling** [FrontendSophie/hexo-infinite-scroll#6]
It's not working on my website!

I use [materialized theme](https://github.com/theme-materialized/hexo-theme-materialized)

I've tried the solution in #2 . However it doesn't work and showed an error in console:

![image](https://user-images.githubusercontent.com/59298517/77507359-4683f880-6ea3-11ea-96dd-88f17cc176ca.png)

What should I do? 

BTW, my blog site is: sunxling.github.io

**Comment by sunxling** [comment]
Below is my code in head.ejs:

```
    <script src="https://cdn.jsdelivr.net/gh/frontendsophie/hexo-infinite-scroll@2.0.0/dist/main.js"></script>
    <script>
        infiniteScroll({
            item: '.article'
        })
    </script>
```

**Comment by FrontendSophie** [comment]
@sunxling 
Just checked your blog,  The reason why it is not working is because your item class name is neither '.post' nor '.article'.
```
<article class="mdui-card mdui-m-b-5 mdui-hoverable">
```

So Please try: 
```
item: '.mdui-card'
```
instead.
